/**
 * نصوص الواجهة (عربي/إنجليزي) — ممنوع الـ hardcoding في المكونات.
 */
export const strings = {
  ar: {
    appName: 'إستعانة',
    nav: {
      mihrab: 'المحراب',
      athari: 'أثري',
      zad: 'زاد',
      settings: 'الإعدادات',
    },
    status: {
      online: 'متصل',
      offline: 'غير متصل',
      syncing: 'جاري المزامنة...',
    },
    splash: {
      loading: 'جاري التهيئة...',
    },
    actions: {
      logActionDemo: 'تسجيل فعل (تجربة)',
    },
    mihrab: {
      title: 'المحراب',
      subtitle: 'أوقات الصلاة والمحتوى اليومي',
      contentPlaceholder: 'محتوى المحراب (أوقات الصلاة والمحتوى اليومي)',
      toolsTitle: 'أدوات المسلم',
      toolQuran: 'المصحف',
      toolTasbih: 'السبحة',
      toolQibla: 'القبلة',
      tasbihTitle: 'السبحة',
      tasbihReset: 'إعادة تعيين',
      tasbihCount: 'العدد',
      quranLoading: 'جاري تحميل المصحف...',
      quranReady: 'المصحف جاهز للقراءة',
      mushafLabel: 'المصحف الشريف',
      surahListTitle: 'اختر سورة',
      selectSurah: 'اختر سورة للقراءة',
      quranFetchError: 'تعذّر تحميل المصحف. تحقق من الاتصال وحاول مرة أخرى.',
      quranRetryHint: 'تأكد من الاتصال بالإنترنت ثم اضغط إعادة المحاولة.',
      retry: 'إعادة المحاولة',
      backToSurahs: 'العودة إلى السور',
      verseActions: 'إجراءات الآية',
      bookmark: 'علامة مرجعية',
      bookmarkSave: 'حفظ مكان الوقوف',
      heartTouched: 'آية لمست قلبي',
      heartTouchedSave: 'حفظ الآية في قائمة القلب',
      hifzMode: 'وضع التسميع',
      hifzModeHint: 'إخفاء النص وإظهاره عند النقر',
      fontSize: 'حجم الخط',
      theme: 'المظهر',
      themeLight: 'فاتح',
      themeDark: 'داكن',
      themeSepia: 'سيبيا',
    },
    athari: {
      title: 'أثري',
      subtitle: 'سجل أفعالك اليومية',
      contentPlaceholder: 'سجل الأفعال اليومية',
      progressLabel: 'إنجاز اليوم',
      onboarding: {
        headline: 'اختر فئتك العمرية',
        subline: 'لنُعدّ لك قائمة أفعال يومية مناسبة',
        ageChild: 'طفل (حتى 12)',
        ageTeen: 'مراهق (13–17)',
        ageAdult: 'بالغ (18+)',
        cta: 'متابعة',
        changeLater: 'يمكنك تغيير الفئة لاحقاً من الإعدادات',
      },
      tasks: {
        fajr: 'صلاة الفجر',
        dhuhr: 'صلاة الظهر',
        asr: 'صلاة العصر',
        maghrib: 'صلاة المغرب',
        isha: 'صلاة العشاء',
        dhikr_morning: 'أذكار الصباح',
        dhikr_evening: 'أذكار المساء',
        quran: 'قراءة قرآن',
        istighfar: 'استغفار',
        duaa: 'دعاء',
        prayer_simple: 'الصلاة',
        dhikr_short: 'أذكار',
        quran_verse: 'آية من القرآن',
      },
    },
    zad: {
      title: 'زاد',
      subtitle: 'زادك من القرآن والأذكار',
      contentPlaceholder: 'زادك من القرآن والأذكار',
      dailyWisdomTitle: 'حكمة اليوم',
      shareAsImage: 'مشاركة كصورة',
      sourceLabel: 'المصدر',
      wisdomTypeQuran: 'آية قرآنية',
      wisdomTypeHadith: 'حديث شريف',
      noWisdom: 'لا توجد حكمة متاحة اليوم.',
    },
    settings: {
      title: 'الإعدادات',
      subtitle: 'الملف الشخصي والإشعارات',
      profileItem: 'الملف الشخصي',
      profileItemSupporting: 'الاسم والعمر',
      notificationsItem: 'الإشعارات',
      notificationsItemSupporting: 'التردد والوضع الليلي',
    },
    common: {
      save: 'حفظ',
      cancel: 'إلغاء',
      back: 'رجوع',
    },
  },
  en: {
    appName: 'Esteana',
    nav: {
      mihrab: 'Mihrab',
      athari: 'My Trace',
      zad: 'Provisions',
      settings: 'Settings',
    },
    status: {
      online: 'Online',
      offline: 'Offline',
      syncing: 'Syncing...',
    },
    splash: {
      loading: 'Loading...',
    },
    actions: {
      logActionDemo: 'Log action (demo)',
    },
    mihrab: {
      title: 'Mihrab',
      subtitle: 'Prayer times and daily content',
      contentPlaceholder: 'Prayer times and daily content',
      toolsTitle: 'Muslim Tools',
      toolQuran: 'Quran',
      toolTasbih: 'Tasbih',
      toolQibla: 'Qibla',
      tasbihTitle: 'Tasbih',
      tasbihReset: 'Reset',
      tasbihCount: 'Count',
      quranLoading: 'Loading Quran...',
      quranReady: 'Quran ready to read',
      mushafLabel: 'The Noble Quran',
      surahListTitle: 'Choose a surah',
      selectSurah: 'Choose a surah to read',
      quranFetchError: 'Could not load the Quran. Check your connection and try again.',
      quranRetryHint: 'Make sure you are connected to the internet then tap Retry.',
      retry: 'Retry',
      backToSurahs: 'Back to surahs',
      verseActions: 'Verse actions',
      bookmark: 'Bookmark',
      bookmarkSave: 'Save reading position',
      heartTouched: 'Heart touched',
      heartTouchedSave: 'Save verse to heart list',
      hifzMode: 'Hifz mode',
      hifzModeHint: 'Hide text, show on tap',
      fontSize: 'Font size',
      theme: 'Theme',
      themeLight: 'Light',
      themeDark: 'Dark',
      themeSepia: 'Sepia',
    },
    athari: {
      title: 'My Trace',
      subtitle: 'Your daily actions log',
      contentPlaceholder: 'Daily actions log',
      progressLabel: "Today's progress",
      onboarding: {
        headline: 'Choose your age group',
        subline: "We'll set a daily checklist that fits you",
        ageChild: 'Child (up to 12)',
        ageTeen: 'Teen (13–17)',
        ageAdult: 'Adult (18+)',
        cta: 'Continue',
        changeLater: 'You can change this later in Settings',
      },
      tasks: {
        fajr: 'Fajr',
        dhuhr: 'Dhuhr',
        asr: 'Asr',
        maghrib: 'Maghrib',
        isha: 'Isha',
        dhikr_morning: 'Morning dhikr',
        dhikr_evening: 'Evening dhikr',
        quran: 'Quran reading',
        istighfar: 'Istighfar',
        duaa: 'Supplication',
        prayer_simple: 'Prayer',
        dhikr_short: 'Dhikr',
        quran_verse: 'A verse of Quran',
      },
    },
    zad: {
      title: 'Provisions',
      subtitle: 'Quran and dhikr',
      contentPlaceholder: 'Quran and dhikr',
      dailyWisdomTitle: 'Wisdom of the Day',
      shareAsImage: 'Share as image',
      sourceLabel: 'Source',
      wisdomTypeQuran: 'Quran',
      wisdomTypeHadith: 'Hadith',
      noWisdom: 'No wisdom available for today.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Profile and notifications',
      profileItem: 'Profile',
      profileItemSupporting: 'Name and age',
      notificationsItem: 'Notifications',
      notificationsItemSupporting: 'Frequency and quiet hours',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      back: 'Back',
    },
  },
};

const defaultLocale = 'ar';

/**
 * @param {'ar'|'en'} [locale]
 * @returns {typeof strings.ar}
 */
export function getStrings(locale = defaultLocale) {
  return strings[locale] ?? strings.ar;
}

export { defaultLocale };
